### ISSUE TITLE
Benchmarking lab 3.4.x. vs 3.0.x ?

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/benchmarks#116]
I added a manual run for seeing benchmarking 3.4.x vs 3.0.x but it failed: https://github.com/jupyterlab/benchmarks/actions/runs/2995288042

Is there a minimal version of the lab version that can be benchmarked?

**Comment by vidartf** [comment]
Thanks! 👍

**Comment by fcollonval** [comment]
mmmh... apparently the accessibility `role` attribute was added later than 3.0. So the selectors are not working. You may give a try by using `jupyterlab-1-2` for 3.0.x.
