### ISSUE TITLE
Having other large notebooks open while tab switching

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/benchmarks#124]
### Problem
There were some recent issues where a change that gave a performance improvement when just 2 notebooks were open and switched between, it gave a performance penalty when multiple large files were open.

### Proposed Solution

Keep multiple copies of large files open during benchmarking (maybe as a new class, maybe as a change to existing). As long has they have been displayed once before switching between tabs, all their elements (lumino and/or DOM) will still affect the performance. This should be closer to many symptomatic cases that users will see during their normal work.

**Comment by fcollonval** [comment]
~10 notebooks could be a good test

**Comment by krassowski** [comment]
I believe this will be addressed by https://github.com/jupyterlab/benchmarks/pull/143 which runs all the ui-profiler scenarios across three configurations:
- `empty.ipynb` - empty notebook
- `div-span-svg-5k-each.ipynb` - notebook with 5000 `<div>`, 5000 `<span>` and 5000 `<svg>` elements
- `all-html-elements-100-each.ipynb` - notebook with 100 elements for each known HTML tag
