### ISSUE TITLE
Add cpu/mem on which the benchmarks has been run in the csv outtput

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/benchmarks#23]

**Comment by goanpeca** [comment]
Maybe we could use something like this

https://systeminformation.io/ ?

Looked into https://stackoverflow.com/questions/36816181/get-view-memory-cpu-usage-via-nodejs

If you have any suggestions let me know! :-)

**Comment by echarles** [comment]
The browser (chrome/firefox) version would be a good addition also.

Then comes the question how to store those values.

- In a separated file?
- In additional columns to the current CSV file (with a lot a duplications, but why not...)?
- In a new file format (JSON) that would allow more structured schema, not sure how vega can easily read that?

**Comment by goanpeca** [comment]
>In a separated file?

Separate file and have vega read that one too ?

**Comment by echarles** [comment]
> Separate file and have vega read that one too ?

Don't think it is possible. It would be just for historical info, not for plot.

**Comment by goanpeca** [comment]
>Don't think it is possible

yeah.

Ok, are we storing all these runs and plots somewhere in the repo? (I could not find any)

**Comment by goanpeca** [comment]
Should we add the Firefox and Chromium version?

**Comment by echarles** [comment]
> Ok, are we storing all these runs and plots somewhere in the repo? (I could not find any)

We are not storing them. My intuition was to publish relevant graphs on the website. We can link from the website to out.csv if stored in the repo if you find it useful.

**Comment by echarles** [comment]
> Should we add the Firefox and Chromium version?

We can add that info in some metadata file associated to the out.csv. The versions can be taken manually if we don't have the script doing that for now.

**Comment by goanpeca** [comment]
Ok. I am going to move the Shadow Doms tests to Github CI and upload artifacts ready for consumption to be able to iterate quicker, while I look at the Chrome85 thing on my local computer.
