### ISSUE TITLE
Distribute benchmarks more easily

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/benchmarks#3]
We should distribute the benchmark package in some way to make it easier to run against in development jupyterlab or published jupyterlab.

We might also consider using rollup/webpack to pre-bundle it, so we can avoid some weirdness  with stdlib that it does on postinstall that doesn't always work with yarn.

**Comment by kgryte** [comment]
To be clear, the `yarn` issue arises due to slower network connections on remote filesystems, such as NFS. This is not necessarily an issue with `stdlib`. However, there are straightforward workarounds to avoid such issues. Notably, vendoring.

**Comment by fcollonval** [comment]
Closing as the benchmark tests can be run from GitHub CI.
