### ISSUE TITLE
Run benchmark on CI for the virtual notebook branch

### ISSUE THREAD

**Issue by echarles** [jupyterlab/benchmarks#55]
We should run the benchmark in CI to measure the effect of the virtual notebook branch (now released as jupyterlab 2.3.0a1).

This has been asked by @telamonian 

cc/ @goanpeca

**Comment by goanpeca** [comment]
Will work on this!

**Comment by echarles** [comment]
Would be great to have also figures for the window version of the virtual notebook hosted

```
git clone https://github.com/datalayer-contrib/jupyterlab -b virtual_notebook/window
```

**Comment by echarles** [comment]
Fixed in https://github.com/jupyterlab/benchmarks/pull/60
